//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORRECTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CORRECTION()
        {
            this.INSPECTION = new HashSet<INSPECTION>();
        }
    
        public int ID { get; set; }
        public int equipmentID { get; set; }
        public int hazardID { get; set; }
        public string action { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTION> INSPECTION { get; set; }
        public virtual HAZARD HAZARD { get; set; }
    }
}
