//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAZARDOBSERVED
    {
        public bool Status { get; set; }
        public int ID { get; set; }
        public int InspectionDetailID { get; set; }
        public int HazardID { get; set; }
        public string problemFound { get; set; }
        public string actionRequired { get; set; }
        public Nullable<bool> urgentAction { get; set; }
    
        public virtual INSPECTIONDETAILS INSPECTIONDETAILS { get; set; }
        public virtual HAZARD HAZARD { get; set; }
    }
}
