//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAZARDOBSERVED
    {
        public int Id { get; set; }
        public string HazardDescription { get; set; }
        public Nullable<int> FormID { get; set; }
        public string Comments { get; set; }
        public bool Status { get; set; }
    
        public virtual INSPECTION INSPECTION { get; set; }
    }
}
